#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
# $scripts/wall $config/wallpapers/cloud.png &
# hyprpaper &

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Conky
#killall -q conky
#/home/mattia/.dotfiles/.config/bspwm/conky/conky.sh &

# Bluetooth manager
blueberry-tray &

# Blue-light filter
wlsunset -t 3500 -T 5000 &

#swayidle daemon and inhibitor
# swayidle -w \
#   timeout 600 'hyprlock' \
#   before-sleep 'hyprlock' &

# Hypridle and inhibitor
# hypridle &
wayland-pipewire-idle-inhibit -w &
caffeine &
# wl-mpris-idle-inhibit &

# nordvpn service
systemctl start nordvpnd.service &

# Megasync and pcloud
sleep 5 && ~/AppImages/pcloud &
sleep 5 && env QT_QPA_PLATFORM=xcb megasync &

# Automatic mounting
udiskie &

# Launch swww and wallpaper script
sleep 5 && swww init && ~/.local/bin/wallpaper ~/.config/wallpapers/ &

# Network manager
nm-applet &

# Set soruce volume
pamixer --default-source --set-volume 30
