#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &
$scripts/tools/dynamic &

# wallpaper
# $scripts/wall $config/wallpapers/cloud.png &
hyprpaper &

# effects
$scripts/rgb &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Conky
#killall -q conky
#/home/mattia/.dotfiles/.config/bspwm/conky/conky.sh &

# Bluetooth manager
blueman-applet &

# Blue-light filter
wlsunset &

#swayidle daemon and inhibitor
swayidle -w &
sway-audio-idle-inhibit &

# nordvpn service
systemctl start nordvpnd.service &

# Megasync
sleep 10 && megasync &
