-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local lock_cmd = "pidof hyprlock || hyprlock"

local suspend_cmd = "pidof steam || systemctl suspend || loginctl suspend"

-- fuck nvidia

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        before_sleep_cmd = "loginctl lock-session",
    },
})

-- listener {

--     timeout = 180 # 3mins

--     on-timeout = loginctl lock-session

-- }

--

-- listener {

--     timeout = 240 # 4mins

--     on-timeout = hyprctl dispatch dpms off

--     on-resume = hyprctl dispatch dpms on

-- }

--

hl.config({
    listener = {
        timeout = 600,
        -- 10mins
        on-timeout = "pidof hyprlock || hyprlock",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

-- listener {

--     timeout = 600 # 10mins

--     on-timeout = $suspend_cmd

-- }
