-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- exec = export SLURP_ARGS='-d -c FFFFFFBB -b 00677D44 -s 00000000'

hl.config({
    general = {
        col.active_border = "rgba(E0E2EF39)",
        col.inactive_border = "rgba(8A90A530)",
    },
})

hl.config({
    misc = {
        background_color = "rgba(10131CFF)",
    },
})

hl.plugin("hyprbars", function()
    -- Honestly idk if it works like css, but well, why not
    bar_text_font = { "Rubik", "Geist", "AR One Sans", "Reddit Sans", "Inter", "Roboto", "Ubuntu", "Noto Sans", "sans-serif" },
    bar_height = 30,
    bar_padding = 10,
    bar_button_padding = 5,
    bar_precedence_over_border = true,
    bar_part_of_window = true,
    bar_color = "rgba(10131CFF)",
    col.text = "rgba(E0E2EFFF)",
    -- example buttons (R -> L)
    -- hyprbars-button = color, size, on-click
    hyprbars-button = { "rgb(E0E2EF)", 13, "󰖭", "hyprctl dispatch killactive" },
    hyprbars-button = { "rgb(E0E2EF)", 13, "󰖯", "hyprctl dispatch fullscreen 1" },
    hyprbars-button = { "rgb(E0E2EF)", 13, "󰖰", "hyprctl dispatch movetoworkspacesilent special" },
end)

hl.window_rule({
    name  = "bordercolor_rgba_59d",
    match = {
        pinned = 1,
    },
    -- TODO: review rule: "bordercolor rgba(59D5F8AA) rgba(59D5F877)"
})
