-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ######### Input method ########## 

-- See https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland

hl.env("QT_IM_MODULE", "fcitx")

hl.env("XMODIFIERS", "@im=fcitx")

-- env = GTK_IM_MODULE, wayland   # Crashes electron apps in xwayland

-- env = GTK_IM_MODULE, fcitx     # My Gtk apps no longer require this to work with fcitx5 hmm  

hl.env("SDL_IM_MODULE", "fcitx")

hl.env("GLFW_IM_MODULE", "ibus")

hl.env("INPUT_METHOD", "fcitx")

-- ############ Themes #############

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

-- env = QT_STYLE_OVERRIDE,kvantum

-- env = WLR_NO_HARDWARE_CURSORS, 1

-- ######## Screen tearing #########

-- env = WLR_DRM_NO_ATOMIC, 1

-- ######## Virtual envrionment #########

hl.env("XDG_STATE_HOME", "local_var_HOME/.local/state")

hl.env("ILLOGICAL_IMPULSE_VIRTUAL_ENV", "local_var_XDG_STATE_HOME/ags/.venv")

-- ############ Others #############
