-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Bar, wallpaper

-- exec-once = swww-daemon --format xrgb



-- Input method


-- Core components (authentication, lock screen, notification daemon)



-- exec-once = hypridle



-- Some fix idk


-- Audio


-- Clipboard: history

-- exec-once = wl-paste --watch cliphist store &



-- Cursor


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/geoclue-2.0/demos/agent & gammastep")
    hl.exec_cmd("ags &")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor Catppuccin-Mocha-Light 24")
end)
