;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				autopair-insert-opening
				autopair-skip-close-maybe
				evil-append
				evil-backward-char
				evil-delete-char
				evil-exit-visual-state
				evil-force-normal-state
				evil-forward-char
				evil-insert
				evil-next-line
				evil-normal-state
				evil-previous-line
				evil-substitute
				evil-visual-char
				))

(setq mc/cmds-to-run-once
      '(
				))
