-- return { -- override nvim-cmp plugin
--   "hrsh7th/nvim-cmp",
--   enabled = true,
--   -- override the options table that is used in the `require("cmp").setup()` call
--   opts = function(_, opts)
--     -- opts parameter is the default options table
--     -- the function is lazy loaded so cmp is able to be required
--     local cmp = require "cmp"
--     -- modify the sources part of the options table
--     opts.sources = cmp.config.sources {
--       { name = "luasnip", priority = 1000 },
--       { name = "html-css" },
--       { name = "nvim_lsp", priority = 900 },
--       { name = "text", priority = 800 },
--       {
--         name = "buffer",
--         priority = 500,
--         option = {
--           get_bufnrs = function() return vim.api.nvim_list_bufs() end,
--         },
--       },
--       { name = "path", priority = 250 },
--     }
--   end,
-- }
return {
	"hrsh7th/nvim-cmp",
	enabled = true,
	version = false, -- last release is way too old
	-- event = "InsertEnter",
	-- dependencies = {
	-- 	"hrsh7th/cmp-nvim-lsp",
	-- 	"hrsh7th/cmp-buffer",
	-- 	"hrsh7th/cmp-path",
	-- },
	-- -- Not all LSP servers add brackets when completing a function.
	-- -- To better deal with this, LazyVim adds a custom option to cmp,
	-- -- that you can configure. For example:
	-- --
	-- -- ```lua
	-- -- opts = {
	-- --   auto_brackets = { "python" }
	-- -- }
	-- -- ```
	-- opts = function()
	-- 	vim.api.nvim_set_hl(0, "CmpGhostText", { link = "Comment", default = true })
	-- 	local cmp = require("cmp")
	-- 	local defaults = require("cmp.config.default")()
	-- 	local auto_select = true
	-- 	local options = {
	-- 		auto_brackets = {}, -- configure any filetype to auto add brackets
	-- 		completion = {
	-- 			completeopt = "menu,menuone,noinsert" .. (auto_select and "" or ",noselect"),
	-- 		},
	-- 		preselect = auto_select and cmp.PreselectMode.Item or cmp.PreselectMode.None,
	-- 		mapping = cmp.mapping.preset.insert({
	-- 			["<C-b>"] = cmp.mapping.scroll_docs(-4),
	-- 			["<C-f>"] = cmp.mapping.scroll_docs(4),
	-- 			["<C-j>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
	-- 			["<C-k>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
	-- 			["<C-Space>"] = cmp.mapping.complete(),
	-- 			["<C-CR>"] = function(fallback)
	-- 				cmp.abort()
	-- 				fallback()
	-- 			end,
	-- 		}),
	-- 		sources = cmp.config.sources({
	-- 			{ name = "lazydev" },
	-- 			{ name = "nvim_lsp" },
	-- 			{ name = "path" },
	-- 			{ name = "buffer" },
	-- 			{ name = "html-css" },
	-- 		}),
	-- 		experimental = {
	-- 			-- only show ghost text when we show ai completions
	-- 			ghost_text = vim.g.ai_cmp and {
	-- 				hl_group = "CmpGhostText",
	-- 			} or false,
	-- 		},
	-- 		sorting = defaults.sorting,
	-- 	}
	-- 	options = vim.tbl_deep_extend("force", options, require("nvchad.cmp"))
	-- 	require("cmp").setup(options)
	--
	-- 	return options
	-- end,
	-- -- main = "lazyvim.util.cmp",
}
