-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ! Auto-generated file. Do not edit directly.

-- Remove source = ./dms/colors.conf from your config to override.

local primary = "rgb(aec6ff)"

local outline = "rgb(919191)"

local error = "rgb(ffb4ab)"

hl.config({
    general = {
        col.active_border = "rgb(aec6ff)",
        col.inactive_border = "rgb(919191)",
    },
})

hl.config({
    group = {
        col.border_active = "rgb(aec6ff)",
        col.border_inactive = "rgb(919191)",
        col.border_locked_active = "rgb(ffb4ab)",
        col.border_locked_inactive = "rgb(919191)",
        groupbar = {
            col.active = "rgb(aec6ff)",
            col.inactive = "rgb(919191)",
            col.locked_active = "rgb(ffb4ab)",
            col.locked_inactive = "rgb(919191)",
        },
    },
})
