-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-lavender-cursors")
hl.env("XCURSOR_THEME", "catppuccin-mocha-lavender-cursors")
hl.env("HYPRCURSOR_SIZE", "20")
hl.env("XCURSOR_SIZE", "20")
